In [28]:
from bs4 import BeautifulSoup
import requests
import smtplib
import datetime
import time

In [36]:
url='https://www.amazon.in/DUDEME-Sleeve-Cotton-Programmer-Developer/dp/B0CYLS8RR2/ref=sr_1_18?dib=eyJ2IjoiMSJ9.qRY2KKBIZB0_pBhCbMpSdeZXc9ihpmoURyBs-u5BP1tz_91CRG1BIJF1HnZ145jPS1b0TcfB9gKimgBToi9dPp3ZADxyJDEChJTVJa2UGZaN5h5DWOcWzYoyBTefM0uv0iaWMte32XExYNKgCBbqX4kAXSULv7k6Vr1tiLEQOZV740tquJmruUnDwQUUrbbnBM5KfA4G4MPfSOnBtqwg8cmZcGWbcVrtEY0vzd5TMJYQ2JU6yUNKO3piKnp_ILK4uB8VbuvdPbOH2r-0Xm7LU_dRXgUdn6fLIsGoMEG-Ry8.ryf-jba3hOTbHJz5o87XsHXc0SMMVbjkR9jK5NRkhGw&dib_tag=se&keywords=data%2Bscience%2Btshirt&qid=1782363882&sr=8-18&th=1&psc=1'
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}
page=requests.get(url,headers=headers)

soup1=BeautifulSoup(page.content,'html.parser')

soup2=BeautifulSoup(soup1.prettify(),'html.parser')
title=soup2.find(id='productTitle').get_text()
price=soup2.find(class_="a-price-whole").get_text()
print(title)
print(price)

print('Hi')

                 DUDEME AWS Half Sleeve 100% Cotton 180 GSM T-Shirt


                   499

Hi

In [37]:
title=title.strip()
price=price.strip()
print(title)
print(price)
# type(price)

DUDEME AWS Half Sleeve 100% Cotton 180 GSM T-Shirt
499

In [38]:
import datetime
today=datetime.date.today()
print(today)

2026-06-26

In [39]:
import csv
header=['Title','Price','Date']
data=[title,price,today]

with open('AmazonWebScrapingDataset(n).csv','w',newline='',encoding='UTF-8') as f:
    writer=csv.writer(f)
    writer.writerow(header)
    
    writer.writerow(data)

In [40]:
import pandas as pd
df=pd.read_csv(r"C:\DATA ANALYST\python_DA\original_practice_python\AmazonWebScrapingDataset(n).csv")

In [41]:
df

,Title,Price,Date,Time
0,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:40:55
1,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:41:07
2,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:45:57
3,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:46:09

In [42]:
# for appending the csv file
import csv
with open('AmazonWebScrapingDataset(n).csv','a+',newline='',encoding='UTF-8') as f:
    writer=csv.writer(f)
    writer.writerow(data)

In [43]:
from bs4 import BeautifulSoup
import requests
import smtplib
import datetime
import time
from time import timezone
import pytz

In [50]:
def check_price():
    from bs4 import BeautifulSoup
    import requests
    import smtplib
    import datetime
    import time
    from time import timezone
    import pytz
   
    url='https://www.amazon.in/Seek-Buy-Love-Programmer-Sarcastic/dp/B0FNLVFMM6/ref=sr_1_18?crid=3O52PSQC5VWKQ&dib=eyJ2IjoiMSJ9.2LfQ4wkvlB_HsfBs84SegrcSt88xhZYg6NvIzMlKVxjsUq80UfTBjLWJ2qMIZ89OU1wsiyyeUqoxSomgwj_T6pauZDsxxnjwFJEN-LACPnYTg8Tac5W2zZV5S7msOGhZ1Y0bmJcmlUlVQbjhqMb2ejv0VCNkFUs-WPDG0_HSrr8_gb9fhxeMWTFXG0YUiOkRtnTbZ08SLlCuvKWGo26BVBvfBa8brEcaGDaARpFlEY8SnfxsaEgBT89V7TnDW6FthLIUYEOGXAOuWL9T0HTMlDlNELiL9Qywodhmxxu01fE.ocQ0FrorxFHcQ_cgR5IArUtgPVN8Ga5vc2Z024zZy94&dib_tag=se&keywords=data%2Bt%2Bshirt&qid=1782452272&sprefix=data%2Bt%2Bshirt%2Caps%2C381&sr=8-18&th=1&psc=1'
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    page=requests.get(url,headers=headers)

    IST=pytz.timezone('Asia/Kolkata')
    soup1=BeautifulSoup(page.content,'html.parser')
    soup2=BeautifulSoup(soup1.prettify(),'html.parser')
    title=soup2.find(id='productTitle').get_text()
    price=soup2.find(class_="a-price-whole").get_text()
    title=title.strip()
    price=price.strip()
    import datetime
    ist_now=datetime.datetime.now(IST)
    timee=ist_now.strftime("%H: %M: %S")
    datee=ist_now.strftime("%Y/%m/%d")
    #today=datetime.date.today()
    print(f"Date: {datee}, Time: {timee}")
    import csv
    header=['Title','Price','Date','Time']
    data=[title,price,datee, timee]
    with open("C:\DATA ANALYST\python_DA\original_practice_python\AmazonWebScrapingDataset(n).csv",'a+',newline='',encoding='UTF-8') as f:
        writer=csv.writer(f)
        writer.writerow(data)

In [51]:
while(True):
    check_price()
    time.sleep(6)

Date: 2026/06/26, Time: 12: 01: 55
Date: 2026/06/26, Time: 12: 02: 06

KeyboardInterrupt:

In [52]:
import pandas as pd
df=pd.read_csv(r"C:\DATA ANALYST\python_DA\original_practice_python\AmazonWebScrapingDataset(n).csv")
print(df)

                                               Title  Price        Date  \
0  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  26-06-2026
1  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  26-06-2026
2  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  26-06-2026
3  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  26-06-2026
4  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  2026/06/26
5  Data is The New Bacon T-Shirt, Funny Foodie Sh...    499  2026/06/26

         Time
0    11:40:55
1    11:41:07
2    11:45:57
3    11:46:09
4  12: 01: 55
5  12: 02: 06

In [47]:
df

,Title,Price,Date,Time
0,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:40:55
1,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:41:07
2,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:45:57
3,"Data is The New Bacon T-Shirt, Funny Foodie Sh...",499,26-06-2026,11:46:09

In [1]:
print('Ji')

Ji

In [ ]:
<span id="productTitle" class="a-size-large product-title-word-break">        DUDEME AWS Half Sleeve 100% Cotton 180 GSM T-Shirt       </span>

In [17]:
import requests
page = requests.get(url, headers=headers)
print(page.text[:1000])  # Prints the first 1000 characters of what your script actually sees

<!DOCTYPE html>
<!--[if lt IE 7]> <html lang="en-us" class="a-no-js a-lt-ie9 a-lt-ie8 a-lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html lang="en-us" class="a-no-js a-lt-ie9 a-lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html lang="en-us" class="a-no-js a-lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="a-no-js" lang="en-us"><!--<![endif]--><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title dir="ltr">Amazon.in</title>
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/AmazonUI-3c913031596ca78a3768f4e934b1cc02ce238101.secure.min._V1_.css">
<script>

if (true === true) {
    var ue_t0 = (+ new Date()),
        ue_csm = window,
        ue = { t0: ue_t0, d: function() { return (+new Date() - ue_t0); } },
        ue_furl = "fls-eu.amazon.in",
        ue_mid = "A21TJRUUN4KGV",

In [7]:
import datetime
import time
from time import timezone
import pytz

In [12]:
IST=pytz.timezone('Asia/Kolkata')
ist_now=datetime.datetime.now(IST)
time=ist_now.strftime('%H:%M:%S')
print(time)

10:34:46

In [38]:
ist_date=datetime.datetime.now(IST)
date=ist_date.strftime('%Y/%m/%d')
print(date)

2026/06/26

In [56]:
import pytz
import datetime
IST=pytz.timezone('Asia/Kolkata')
ist_now=datetime.datetime.now(IST)
print(ist_now)

2026-06-26 11:18:06.799933+05:30

In [ ]:
"C:\DATA ANALYST\python_DA\original_practice_python\AmazonWebScrapingDataset(n).csv"